language: go

go:
  - 1.12.x

install:
  - go get -v ./...
  - go build ./...
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
